language: node_js
node_js:
  - 22
dist: jammy
cache:
  directories:
    - $HOME/.cache/yarn 
    - node_modules
    - .next/cache
script:
  - yarn install
  - yarn build
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: out
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
